# R/bc_aquarius.R
#
# hydrocan adapter for the BC Government Aquarius hydrometric network.
#
# The Aquarius export endpoint is public and requires no authentication.
# The station list is generated by data-raw/sysdata.R from the portal's
# Data/Data_List JSON endpoint and stored as bc_aquarius_stations in
# R/sysdata.rda. The list is restricted to stations exposing a "Working"
# discharge or stage series, the only datasets this adapter can fetch via
# {parameter}.Working@{id}; the notes column records which are available.
# The endpoint gates content behind a disclaimer that sets a session cookie;
# the data-raw script accepts it before querying. Re-run that script and
# commit R/sysdata.rda when the station network changes.
#
# Daily aggregation is handled server-side by Aquarius (IntervalPoints=Daily).
# StartTime/EndTime are UTC day boundaries, not local BC time, and daily aggregates are computed over UTC days.
# Sub-daily data is returned at the native logger interval.
# There is no separate hourly tier in the hydrocan adapter contract;
# hc_read_flows() covers all sub-daily data.
#
# Approval level is fetched for sub-daily data and mapped to quality_code
# (raw numeric string) and qf_desc (human-readable label). The mapping is
# documented in every CSV header:
#   800=WORKING, 900=IN REVIEW, 950=REVIEWED, 1200=APPROVED
#
# Note: the daily Aquarius export does not include an approval level column,
# so quality_code and qf_desc are NA for daily data.


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

.BC_AQUARIUS_UNIT_DISCHARGE <- 350L  # m3/s
.BC_AQUARIUS_UNIT_STAGE     <- 306L  # m

# Approval level mapping documented in Aquarius CSV header line 2
.BC_AQUARIUS_APPROVAL_MAP <- c(
  "800"  = "WORKING",
  "900"  = "IN REVIEW",
  "950"  = "REVIEWED",
  "1200" = "APPROVED"
)


# ---------------------------------------------------------------------------
# Internal helpers — HTTP layer
# ---------------------------------------------------------------------------

# Build the Aquarius export URL for a given station and parameter.
# interval: one of "PointsAsRecorded" (default, native logger rate),
#           "Hourly", or "Daily".
.build_aquarius_url <- function(stn_number, parameter, start_time, end_time,
                                unit_id  = 350L,
                                interval = "PointsAsRecorded") {
  parameter  <- tools::toTitleCase(parameter)
  data_set   <- glue::glue("{parameter}.Working@{stn_number}")
  conversion <- if (interval == "Daily") "Aggregate" else "Instantaneous"

  httr2::url_modify(
    "https://bcmoe-prod.aquaticinformatics.net/Export/DataSet",
    query = list(
      DataSet            = data_set,
      Calendar           = "CALENDARYEAR",
      StartTime          = start_time,
      EndTime            = end_time,
      DateRange          = "Custom",
      UnitID             = unit_id,
      Conversion         = conversion,
      IntervalPoints     = interval,
      ApprovalLevels     = "True",
      Qualifiers         = "False",
      Step               = 1,
      ExportFormat       = "csv",
      Compressed         = "false",
      RoundData          = "False",
      GradeCodes         = "False",
      InterpolationTypes = "False",
      Timezone           = 0
    )
  )
}

# Fetch data from Aquarius and return a tibble with columns:
#   timestamp, value, quality_code, qf_desc
#
# Aquarius produces different CSV formats depending on interval:
#
#   Sub-daily: Timestamp (UTC), Value, Approval Level       (3 columns)
#   Daily:     Start of Interval (UTC), End of Interval (UTC), Value  (3 columns)
#
# Both have 3 columns so we detect format by reading the header line (line 6)
# and checking for "Start of Interval". The daily export does not include an
# approval level column; quality_code and qf_desc are NA for daily data.
.get_aquarius_data <- function(...) {
  url   <- .build_aquarius_url(...)
  tfile <- tempfile(fileext = ".csv")

  resp <- httr2::request(url) |>
    httr2::req_user_agent(
      "https://github.com/HakaiInstitute/hakai-streamflow-data"
    ) |>
    httr2::req_perform(path = tfile)

  httr2::resp_check_status(resp)

  # Read header line (line 6) to detect CSV format
  header_line  <- readLines(tfile, n = 6)[6]
  is_daily     <- grepl("Start of Interval", header_line, fixed = TRUE)
  has_approval <- grepl("Approval", header_line, fixed = TRUE)

  if (is_daily) {
    # Daily: Start of Interval, End of Interval, Value
    # No approval column — quality fields are NA
    readr::read_csv(
      tfile,
      skip      = 6,
      col_types = "TTd",
      col_names = c("timestamp", "end_timestamp", "value")
    ) |>
      dplyr::select(-end_timestamp) |>
      dplyr::mutate(
        quality_code = NA_character_,
        qf_desc      = NA_character_
      )

  } else if (has_approval) {
    # Sub-daily with approval: Timestamp, Value, Approval Level
    readr::read_csv(
      tfile,
      skip      = 6,
      col_types = "Tdc",
      col_names = c("timestamp", "value", "approval_level")
    ) |>
      dplyr::mutate(
        quality_code = approval_level,
        qf_desc      = dplyr::recode(
          approval_level,
          !!!.BC_AQUARIUS_APPROVAL_MAP,
          .default = NA_character_
        )
      ) |>
      dplyr::select(-approval_level)

  } else {
    # Fallback: Timestamp, Value only
    readr::read_csv(
      tfile,
      skip      = 6,
      col_types = "Td",
      col_names = c("timestamp", "value")
    ) |>
      dplyr::mutate(
        quality_code = NA_character_,
        qf_desc      = NA_character_
      )
  }
}


# ---------------------------------------------------------------------------
# Adapter functions
# ---------------------------------------------------------------------------

.bc_aquarius_list_stations <- function() bc_aquarius_stations$station_id

.bc_aquarius_list_stations_meta <- function() bc_aquarius_stations

# Sub-daily flows (native logger interval, typically 5 min)
.bc_aquarius_fetch_flows <- function(station_id, start_date, end_date) {
  .get_aquarius_data(
    stn_number = station_id,
    parameter  = "discharge",
    start_time = start_date,
    end_time   = end_date,
    unit_id    = .BC_AQUARIUS_UNIT_DISCHARGE,
    interval   = "PointsAsRecorded"
  ) |>
    dplyr::mutate(
      station_id    = station_id,
      parameter     = "water_discharge",
      unit          = "m3/s",
      provider_name = "bc_aquarius"
    ) |>
    dplyr::select(
      station_id, timestamp, value, parameter,
      unit, provider_name, quality_code, qf_desc
    )
}

# Daily flows (aggregated server-side by Aquarius)
.bc_aquarius_fetch_daily_flows <- function(station_id, start_date, end_date) {
  .get_aquarius_data(
    stn_number = station_id,
    parameter  = "discharge",
    start_time = start_date,
    end_time   = end_date,
    unit_id    = .BC_AQUARIUS_UNIT_DISCHARGE,
    interval   = "Daily"
  ) |>
    dplyr::mutate(
      station_id    = station_id,
      date          = as.Date(timestamp),
      parameter     = "water_discharge",
      unit          = "m3/s",
      provider_name = "bc_aquarius"
    ) |>
    dplyr::select(
      station_id, date, value, parameter,
      unit, provider_name, quality_code, qf_desc
    )
}

# Sub-daily levels (native logger interval, typically 5 min)
.bc_aquarius_fetch_levels <- function(station_id, start_date, end_date) {
  .get_aquarius_data(
    stn_number = station_id,
    parameter  = "stage",
    start_time = start_date,
    end_time   = end_date,
    unit_id    = .BC_AQUARIUS_UNIT_STAGE,
    interval   = "PointsAsRecorded"
  ) |>
    dplyr::mutate(
      station_id    = station_id,
      parameter     = "water_level",
      unit          = "m",
      provider_name = "bc_aquarius"
    ) |>
    dplyr::select(
      station_id, timestamp, value, parameter,
      unit, provider_name, quality_code, qf_desc
    )
}

# Daily levels (aggregated server-side by Aquarius)
.bc_aquarius_fetch_daily_levels <- function(station_id, start_date, end_date) {
  .get_aquarius_data(
    stn_number = station_id,
    parameter  = "stage",
    start_time = start_date,
    end_time   = end_date,
    unit_id    = .BC_AQUARIUS_UNIT_STAGE,
    interval   = "Daily"
  ) |>
    dplyr::mutate(
      station_id    = station_id,
      date          = as.Date(timestamp),
      parameter     = "water_level",
      unit          = "m",
      provider_name = "bc_aquarius"
    ) |>
    dplyr::select(
      station_id, date, value, parameter,
      unit, provider_name, quality_code, qf_desc
    )
}


# ---------------------------------------------------------------------------
# Adapter constructor
# ---------------------------------------------------------------------------

hydrocan_adapter_bc_aquarius <- function() {
  new_hydrocan_adapter(
    "bc_aquarius",
    paste(
      "BC Government Aquarius hydrometric network.",
      "Sub-daily (native logger rate) and daily discharge and stage.",
      "Includes provincial network and other hydrometric stations.",
      "Station list generated from the portal Data_List endpoint by",
      "data-raw/sysdata.R; refresh that script if the network changes.",
      "Approval level available for sub-daily data (quality_code, qf_desc);",
      "NA for daily data as the daily export does not include approval level."
    ),
    .bc_aquarius_list_stations,
    fetch_flows_fn        = .bc_aquarius_fetch_flows,
    fetch_daily_flows_fn  = .bc_aquarius_fetch_daily_flows,
    fetch_levels_fn       = .bc_aquarius_fetch_levels,
    fetch_daily_levels_fn = .bc_aquarius_fetch_daily_levels,
    list_stations_meta_fn = .bc_aquarius_list_stations_meta,
    title = "Hydrometric Stations",
    publisher = "Government of British Columbia",
    license = "CC BY 4.0",
    license_url = "https://creativecommons.org/licenses/by/4.0/",
    terms_url = "https://www2.gov.bc.ca/gov/content/home/disclaimer",
    docs_url = "https://bcmoe-prod.aquaticinformatics.net/Data/GetFile/GettingStartedGuide"
  )
}
